

CREATE TABLE TB_IDS_M (
  TB_NM varchar(20) PRIMARY KEY NOT NULL,
  NEXT_ID decimal(30,0) NOT NULL DEFAULT '0'
  DATA_INPT_ID varchar(50) NOT NULL,
  DATA_INPT_PGM varchar(255) NOT NULL,
  DATA_INPT_DTTM datetime NOT NULL,
  DATA_UPD_ID varchar(50) NOT NULL,
  DATA_UPD_PGM varchar(255) NOT NULL,
  DATA_UPD_DTTM datetime NOT NULL
) ;



CREATE TABLE TB_CL_CD_M (
  CL_CD char(3) PRIMARY KEY NOT NULL,
  CL_CD_NM varchar(60) DEFAULT NULL,
  CL_CD_DESC varchar(200) DEFAULT NULL,
  USE_YN char(1) NOT NULL,
  DATA_INPT_ID varchar(50) NOT NULL,
  DATA_INPT_PGM varchar(255) NOT NULL,
  DATA_INPT_DTTM datetime NOT NULL,
  DATA_UPD_ID varchar(50) NOT NULL,
  DATA_UPD_PGM varchar(255) NOT NULL,
  DATA_UPD_DTTM datetime NOT NULL
) ;



CREATE TABLE TB_CMM_CD_M (
  CD_ID varchar(6) PRIMARY KEY NOT NULL,
  CD_ID_NM varchar(60) DEFAULT NULL,
  CD_ID_DC varchar(200) DEFAULT NULL,
  USE_YN char(1) NOT NULL,
  CL_CD char(3) DEFAULT NULL,
  DATA_INPT_ID varchar(50) NOT NULL,
  DATA_INPT_PGM varchar(255) NOT NULL,
  DATA_INPT_DTTM datetime NOT NULL,
  DATA_UPD_ID varchar(50) NOT NULL,
  DATA_UPD_PGM varchar(255) NOT NULL,
  DATA_UPD_DTTM datetime NOT NULL,
  KEY R_179 (CL_CD),
  CONSTRAINT TB_CMM_CD_M_ibfk_1 FOREIGN KEY (CL_CD) REFERENCES TB_CL_CD_M (CL_CD)
) ;



CREATE TABLE TB_CMM_CD_D (
  CD_DTL_ID varchar(32) PRIMARY KEY NOT NULL, 
  CD_ID varchar(6) NOT NULL,
  CD varchar(15) NOT NULL,
  CD_NM varchar(60) DEFAULT NULL,
  CD_DESC varchar(200) DEFAULT NULL,
  USE_YN char(1) NOT NULL,
  DATA_INPT_ID varchar(50) NOT NULL,
  DATA_INPT_PGM varchar(255) NOT NULL,
  DATA_INPT_DTTM datetime NOT NULL,
  DATA_UPD_ID varchar(50) NOT NULL,
  DATA_UPD_PGM varchar(255) NOT NULL,
  DATA_UPD_DTTM datetime NOT NULL,
  CONSTRAINT TB_CMM_CD_D_ibfk_1 FOREIGN KEY (CD_ID) REFERENCES TB_CMM_CD_M (CD_ID)
) ;



CREATE TABLE TB_ORG_M (
  ORG_ID char(20) PRIMARY KEY  NOT NULL DEFAULT '',
  ORG_NM varchar(20) NOT NULL,
  ORG_DESC varchar(100) DEFAULT NULL,
  DATA_INPT_ID varchar(50) NOT NULL,
  DATA_INPT_PGM varchar(255) NOT NULL,
  DATA_INPT_DTTM datetime NOT NULL,
  DATA_UPD_ID varchar(50) NOT NULL,
  DATA_UPD_PGM varchar(255) NOT NULL,
  DATA_UPD_DTTM datetime NOT NULL
) ;



CREATE TABLE TB_AUTH_GRP_M (
  GRP_ID char(20) PRIMARY KEY NOT NULL DEFAULT '',
  GRP_NM varchar(60) NOT NULL,
  GRP_CRTE_DT char(20) NOT NULL,
  GRP_DESC varchar(100) DEFAULT NULL,
  DATA_INPT_ID varchar(50) NOT NULL,
  DATA_INPT_PGM varchar(255) NOT NULL,
  DATA_INPT_DTTM datetime NOT NULL,
  DATA_UPD_ID varchar(50) NOT NULL,
  DATA_UPD_PGM varchar(255) NOT NULL,
  DATA_UPD_DTTM datetime NOT NULL
) ;



CREATE TABLE TB_USER_M (
  USER_ID varchar(20) PRIMARY KEY NOT NULL,
  ORG_ID char(20) DEFAULT NULL,
  USER_NM varchar(60) NOT NULL,
  PWD varchar(200) NOT NULL,
  EMP_NO varchar(20) DEFAULT NULL,
  IHIDNUM varchar(200) DEFAULT NULL,
  BRTH_DT char(20) DEFAULT NULL,
  FXNO varchar(20) DEFAULT NULL,
  HS_ADRS varchar(100) DEFAULT NULL,
  PWD_HINT varchar(100) NOT NULL,
  PWD_CNSR varchar(100) NOT NULL,
  HS_END_TLNO varchar(4) DEFAULT NULL,
  AREA_NO varchar(4) DEFAULT NULL,
  DTL_ADRS varchar(100) DEFAULT NULL,
  ZIP varchar(6) DEFAULT NULL,
  OFFC_TLNO varchar(20) DEFAULT NULL,
  TLNO varchar(20) DEFAULT NULL,
  EMAL_ADRS varchar(50) DEFAULT NULL,
  OFCPS_NM varchar(60) DEFAULT NULL,
  HS_MID_TLNO varchar(4) DEFAULT NULL,
  GRP_ID char(20) DEFAULT NULL,
  PSTINST_CD char(8) DEFAULT NULL,
  EMP_STUS_CD varchar(15) NOT NULL,
  ENTR_DT datetime DEFAULT NULL,
  DATA_INPT_ID varchar(50) NOT NULL,
  DATA_INPT_PGM varchar(255) NOT NULL,
  DATA_INPT_DTTM datetime NOT NULL,
  DATA_UPD_ID varchar(50) NOT NULL,
  DATA_UPD_PGM varchar(255) NOT NULL,
  DATA_UPD_DTTM datetime NOT NULL
  KEY TB_USER_M_ibfk_2 (GRP_ID),
  KEY TB_USER_M_ibfk_1 (ORG_ID),
  CONSTRAINT TB_USER_M_ibfk_2 FOREIGN KEY (GRP_ID) REFERENCES TB_AUTH_GRP_M (GRP_ID) ON DELETE CASCADE,
  CONSTRAINT TB_USER_M_ibfk_1 FOREIGN KEY (ORG_ID) REFERENCES TB_ORG_M (ORG_ID) ON DELETE CASCADE
) ;



CREATE TABLE TB_BBS_M (
  BBS_ID char(20) PRIMARY KEY NOT NULL,
  BBS_NM varchar(255) NOT NULL,
  BBS_DESC varchar(2400) DEFAULT NULL,
  BBS_KD_CD char(6) NOT NULL,
  BBS_ATTR_CD char(6) NOT NULL,
  RPLY_PSBL_YN char(1) DEFAULT NULL,
  FILE_ATCH_PSBL_YN char(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBR decimal(2,0) NOT NULL,
  ATCH_POSBL_FILE_SIZE decimal(8,0) DEFAULT NULL,
  USE_YN char(1) NOT NULL,
  TMPLAT_ID char(20) DEFAULT NULL,
  DATA_INPT_ID varchar(50) NOT NULL,
  DATA_INPT_PGM varchar(255) NOT NULL,
  DATA_INPT_DTTM datetime NOT NULL,
  DATA_UPD_ID varchar(50) NOT NULL,
  DATA_UPD_PGM varchar(255) NOT NULL,
  DATA_UPD_DTTM datetime NOT NULL
) ;



CREATE TABLE TB_BBS_USE_M (
  BBS_USE_ID varchar(32) PRIMARY KEY NOT NULL,
  BBS_ID char(20) NOT NULL,
  TRGT_ID char(20) NOT NULL DEFAULT '',
  USE_YN char(1) NOT NULL,
  REG_DIVS_CD char(6) DEFAULT NULL,
  DATA_INPT_ID varchar(50) NOT NULL,
  DATA_INPT_PGM varchar(255) NOT NULL,
  DATA_INPT_DTTM datetime NOT NULL,
  DATA_UPD_ID varchar(50) NOT NULL,
  DATA_UPD_PGM varchar(255) NOT NULL,
  DATA_UPD_DTTM datetime NOT NULL,
  CONSTRAINT TB_BBS_USE_M_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES TB_BBS_M (BBS_ID)
) ;



CREATE TABLE TB_BBS_D (
  FILE_DTL_ID varchar(32) PRIMARY KEY NOT NULL ,
  NTT_ID decimal(20,0) NOT NULL,
  BBS_ID char(20) NOT NULL,
  NTT_NO decimal(20,0) DEFAULT NULL,
  NTT_SJ varchar(2000) DEFAULT NULL,
  NTT_CN mediumtext,
  ANSR_YN char(1) DEFAULT NULL,
  PRNT_CTT_NO decimal(10,0) DEFAULT NULL,
  ANSR_LOC int(11) DEFAULT NULL,
  SORT_ORD decimal(8,0) DEFAULT NULL,
  READ_CNT decimal(10,0) DEFAULT NULL,
  USE_YN char(1) NOT NULL,
  NTCE_BGN_DT char(20) DEFAULT NULL,
  NTCE_END_DT char(20) DEFAULT NULL,
  NTCR_ID varchar(20) DEFAULT NULL,
  NTCR_NM varchar(20) DEFAULT NULL,
  PWD varchar(200) DEFAULT NULL,
  ATCH_FILE_ID char(20) DEFAULT NULL,
  DATA_INPT_ID varchar(50) NOT NULL,
  DATA_INPT_PGM varchar(255) NOT NULL,
  DATA_INPT_DTTM datetime NOT NULL,
  DATA_UPD_ID varchar(50) NOT NULL,
  DATA_UPD_PGM varchar(255) NOT NULL,
  DATA_UPD_DTTM datetime NOT NULL,
  /*PRIMARY KEY (NTT_ID,BBS_ID), KEY LETTNBBS_ibfk_1 (BBS_ID),*/
  CONSTRAINT TB_BBS_D_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES TB_BBS_M (BBS_ID)
) ;



CREATE TABLE TB_BBS_ANSR_M (
  BBS_ID char(20) PRIMARY KEY NOT NULL DEFAULT '',
  ANSR_YN char(1) NOT NULL DEFAULT '',  
  DATA_INPT_ID varchar(50) NOT NULL,
  DATA_INPT_PGM varchar(255) NOT NULL,
  DATA_INPT_DTTM datetime NOT NULL,
  DATA_UPD_ID varchar(50) NOT NULL,
  DATA_UPD_PGM varchar(255) NOT NULL,
  DATA_UPD_DTTM datetime NOT NULL,
) ;



CREATE TABLE TB_ENTP_MBR_M (
  ENTP_MBR_ID varchar(20) NOT NULL DEFAULT '',
  ENTP_DIVS_CD char(15) DEFAULT NULL,
  BIZRNO varchar(10) DEFAULT NULL,
  JURIRNO varchar(13) DEFAULT NULL,
  CMPY_NM varchar(60) NOT NULL,
  CXFC varchar(50) DEFAULT NULL,
  ZIP varchar(6) DEFAULT NULL,
  ADRS varchar(100) DEFAULT NULL,
  ENTP_MID_TLNO varchar(4) DEFAULT NULL,
  FXNO varchar(20) DEFAULT NULL,
  IDTY_CD char(15) DEFAULT NULL,
  APLCT_NM varchar(50) NOT NULL,
  ENTR_DT datetime DEFAULT NULL,
  ENTP_MBR_STUS varchar(15) DEFAULT NULL,
  ENTP_MBR_PWD varchar(200) NOT NULL,
  ENTP_MBR_PWD_HINT varchar(100) NOT NULL,
  ENTP_MBR_PWD_CNSR varchar(100) NOT NULL,
  GRP_ID char(20) DEFAULT NULL,
  DTL_ADRS varchar(100) DEFAULT NULL,
  ENTP_END_TLNO varchar(4) DEFAULT NULL,
  AREA_NO varchar(4) DEFAULT NULL,
  APLCT_EMAL_ADRS varchar(50) DEFAULT NULL,
  PRIMARY KEY (ENTP_MBR_ID),
  KEY TB_ENTP_MBR_M_ibfk_1 (GRP_ID),
  CONSTRAINT TB_ENTP_MBR_M_ibfk_1 FOREIGN KEY (GRP_ID) REFERENCES TB_AUTH_GRP_M (GRP_ID) ON DELETE CASCADE
) ;



CREATE TABLE TB_FILE_M (
  ATCH_FILE_ID char(20)PRIMARY KEY NOT NULL,
  CRET_DT datetime NOT NULL,
  USE_YN char(1) NOT NULL,
  dATA_INPT_ID varchar(50) NOT NULL,
  DATA_INPT_PGM varchar(255) NOT NULL,
  DATA_INPT_DTTM datetime NOT NULL,
  DATA_UPD_ID varchar(50) NOT NULL,
  DATA_UPD_PGM varchar(255) NOT NULL,
  DATA_UPD_DTTM datetime NOT NULL
) ;



CREATE TABLE TB_FILE_D (
  FILE_DTL_ID varchar(32) PRIMARY KEY NOT NULL ,
  ATCH_FILE_ID char(20) NOT NULL,
  FILE_SN decimal(10,0) NOT NULL,
  FILE_SAV_LOC varchar(2000) NOT NULL,
  SAVE_FILE_NM varchar(255) NOT NULL,
  ORGI_FILE_NM varchar(255) DEFAULT NULL,
  FILE_EXTSN varchar(20) NOT NULL,
  FILE_CN text,
  FILE_SIZE decimal(8,0) DEFAULT NULL,
  DATA_INPT_ID varchar(50) NOT NULL,
  DATA_INPT_PGM varchar(255) NOT NULL,
  DATA_INPT_DTTM datetime NOT NULL,
  DATA_UPD_ID varchar(50) NOT NULL,
  DATA_UPD_PGM varchar(255) NOT NULL,
  DATA_UPD_DTTM datetime NOT NULL,
  CONSTRAINT TB_FILE_D FOREIGN KEY (ATCH_FILE_ID) REFERENCES TB_FILE_M (ATCH_FILE_ID)
) ;



CREATE TABLE TB_GNRL_MBR_M (
  MBR_ID varchar(20) NOT NULL DEFAULT '',
  PWD varchar(200) NOT NULL,
  PWD_HINT varchar(100) NOT NULL,
  PWD_CNSR varchar(100) NOT NULL,
  MBR_NM varchar(50) NOT NULL,
  ZIP varchar(6) DEFAULT NULL,
  ADRES varchar(100) DEFAULT NULL,
  AREA_NO varchar(4) DEFAULT NULL,
  MBR_STUS_CD varchar(15) DEFAULT NULL,
  DTL_ADRES varchar(100) DEFAULT NULL,
  END_TLNO varchar(4) DEFAULT NULL,
  TLNO varchar(20) DEFAULT NULL,
  GRP_ID char(20) DEFAULT NULL,
  MBR_FXNO varchar(20) DEFAULT NULL,
  MBR_EMAL_ADRES varchar(50) DEFAULT NULL,
  MID_TLNO varchar(4) DEFAULT NULL,
  ENTR_DT datetime DEFAULT NULL,
  DATA_INPT_ID varchar(50) NOT NULL,
  DATA_INPT_PGM varchar(255) NOT NULL,
  DATA_INPT_DTTM datetime NOT NULL,
  DATA_UPD_ID varchar(50) NOT NULL,
  DATA_UPD_PGM varchar(255) NOT NULL,
  DATA_UPD_DTTM datetime NOT NULL,
  PRIMARY KEY (MBR_ID),
  KEY TB_GNRL_MBR_M_ibfk_1 (GRP_ID),
  CONSTRAINT TB_GNRL_MBR_M_ibfk_1 FOREIGN KEY (GRP_ID) REFERENCES TB_AUTH_GRP_M (GRP_ID) ON DELETE CASCADE
) ;



CREATE TABLE TB_SCDL_M (
  SCDL_ID char(20) PRIMARY KEY NOT NULL,
  SCDL_SE char(1) DEFAULT NULL,
  SCDL_DEPT_ID varchar(20) DEFAULT NULL,
  SCDL_KND_CODE varchar(20) DEFAULT NULL,
  SCDL_BGN_DT datetime DEFAULT NULL,
  SCDL_END_DT datetime DEFAULT NULL,
  SCDL_NM varchar(255) DEFAULT NULL,
  SCDL_CN varchar(2500) DEFAULT NULL,
  SCDL_PLACE varchar(255) DEFAULT NULL,
  SCDL_IPCR_CODE char(1) DEFAULT NULL,
  SCDL_CHGR_ID varchar(20) DEFAULT NULL,
  ATCH_FILE_ID char(20) DEFAULT NULL,
  REPT_DIVS_CD char(3) DEFAULT NULL,
  DATA_INPT_ID varchar(50) NOT NULL,
  DATA_INPT_PGM varchar(255) NOT NULL,
  DATA_INPT_DTTM datetime NOT NULL,
  DATA_UPD_ID varchar(50) NOT NULL,
  DATA_UPD_PGM varchar(255) NOT NULL,
  DATA_UPD_DTTM datetime NOT NULL
) ;

CREATE OR REPLACE VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PWD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GRP_ID, USER_SE, ORGNZT_ID ) 
AS  
        SELECT ESNTL_ID, MBR_ID,PWD,MBR_NM,ZIP,ADRES,MBR_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM TB_GNRL_MBR_M
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PWD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GRP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM TB_USER_M
    UNION ALL
        SELECT ESNTL_ID,ENTP_MBR_ID,ENTP_MBR_PWD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM TB_ENTP_MBR_M 
;